### PR TITLE
File added via upload

### PR DESCRIPTION
**Pull request by snovotill**
This is an English user manual for RC3563

### CODE REVIEW

**Comment by snovotill** [comment]
This pull request adds an English user manual for RC3563.

**Comment by ludwich66** [comment]
Hello snovotill, why did you close the PR again. Is there a new version? 
Greetings Ludwich

**Comment by snovotill** [comment]
I closed it because I don't know how to use GitHub. I see that you did 
receive my updates and have merged them. Thanks much =)

**Comment by ludwich66** [comment]
Thanks for your Support!

Ludwich

**Pull request closed without merging**
